import { elementsData } from './elementsData';

export const images = {
    splash_screen_bg: require('./assets/images/veg_fruits_bg.png'),
    game_timer_bg: require('./assets/images/game_timer_bg.png'),
    game_header_bg: require('./assets/images/game_header_bg.png'),
    wooden_plank_bg: require('./assets/images/wooden_plank_bg.png'),
    wooden_plank_texture_modal: require('./assets/images/wooden_plank_texture_modal.png'),
    wooden_plank_with_lives_bg: require('./assets/images/wooden_plank_with_lives_bg.png'),
    caption_bg: require('./assets/images/caption_bg.png'),
    pineapple_btn: require('./assets/images/pineapple_btn.png'),
    cucumber_btn: require('./assets/images/cucumber_btn.png'),
    carrot_btn: require('./assets/images/carrot_btn.png'),
    heart_life: require('./assets/images/heart_life.png'),
    basket_with_fruits_full: require('./assets/images/basket_with_fruits_full.png'),
    basket_with_vegetables_full: require('./assets/images/basket_with_vegetables_full.png'),
    basket_empty: require('./assets/images/basket_empty.png'),
    // elements 
    apple: require('./assets/images/apple.png'),
    banana: require('./assets/images/banana.png'),
    kiwi: require('./assets/images/kiwi.png'),
    lemon: require('./assets/images/lemon.png'),
    orange: require('./assets/images/orange.png'),
    peach: require('./assets/images/peach.png'),
    pear: require('./assets/images/pear.png'),
    pineapple: require('./assets/images/pineapple.png'),
    strawberry: require('./assets/images/strawberry.png'),
    watermelon: require('./assets/images/watermelon.png'),
    tomato: require('./assets/images/tomato.png'),
    pepper: require('./assets/images/pepper.png'),
    potato: require('./assets/images/potato.png'),
    beet: require('./assets/images/beet.png'),
    cabbage: require('./assets/images/cabbage.png'),
    carrot: require('./assets/images/carrot.png'),
    corn: require('./assets/images/corn.png'),
    cucumber: require('./assets/images/cucumber.png'),
}